Loteria/Models/ErrorViewModel.cs
namespace Loteria.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Loteria/Controllers/GanadoresController.cs
using Datos;
using Datos.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text;
using System;

namespace Loteria.Controllers
{
    public class GanadoresController : Controller
    {
        private AppLoteriaContext _context;

        public GanadoresController(AppLoteriaContext context)
        {
            _context = context;
        }

        public async Task<ActionResult> Index()
        {
            var ganadores = await _context.Ganadores
                            .Include(t => t.Tabla)
                            .ThenInclude(c => c.Cartas)
                            .ToListAsync();
            return View(ganadores);
        }

        [HttpPost("[controller]/RegistrarGanador/{TablaId}")]
        public async Task<ActionResult> RegistrarGanador([FromRoute] int TablaId)
        {
            try
            {
                var ganador = new Ganador();
                ganador.FechaHora = DateTime.Now;
                ganador.TablaID = TablaId;
                _context.Ganadores.Add(ganador);

                var result = await _context.SaveChangesAsync();


                if (result > 0)
                {
                    return Ok();
                }
                else
                {
                    return BadRequest(result);
                }

            }
            catch (Exception e)
            {
                return null;
            }
        }

    }
}

Loteria/Controllers/HomeController.cs
using Loteria.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Loteria.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Loteria/Controllers/LoteriaController.cs
using Datos;
using Datos.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Loteria.Controllers
{
    public class LoteriaController : Controller
    {
        private AppLoteriaContext _context;

        public LoteriaController(AppLoteriaContext context)
        {
            _context = context;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet("[controller]/GetCarta")]
        public async Task<IActionResult> GetCarta()
        {
            try
            {
                var cartas = await _context.Cartas.ToListAsync();
                //var data = JsonConvert.DeserializeObject<List<AgentVM>>(result);
                return Ok(cartas);
            }
            catch (Exception e)
            {
                var error = e.InnerException != null ? e.InnerException.ToString() : e.Message;
                return Conflict(error);
            }
        }

        [HttpGet("[controller]/GetTarjetas")]
        public async Task<IActionResult> GetTarjetas()
        {
            try
            {
                //var tablas = await _context.Tablas.Include(c => c.Cartas).ToListAsync();
                var tablas = await _context.Tablas
                        .Include(c => c.Cartas)
                        .Select(x => new Tabla
                        {
                            TablaID = x.TablaID,
                            Nombre = x.Nombre,
                            Cartas = x.Cartas
                        }).ToListAsync(); 
                //var data = JsonConvert.DeserializeObject<List<AgentVM>>(result);
                return Ok(tablas);
            }
            catch (Exception e)
            {
                var error = e.InnerException != null ? e.InnerException.ToString() : e.Message;
                return Conflict(error);
            }
        }

    }
}

Loteria/Views/Ganadores/Index.cshtml
@model List<Datos.Models.Ganador>

<h1 class="titulo">Registro de tablas ganadoras</h1>

<table class="table" style="color:#fff">
    <thead>
        <tr>
            <th>
                Registro
            </th>
            <th>
                Fecha
            </th>
            <th>
                Tabla
            </th>
            <th>
                Juego
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var ganador in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(m => ganador.GanadorID)
                </td>
                <td>
                    @Html.DisplayFor(m => ganador.FechaHora)
                </td>
                <td>
                    @Html.DisplayFor(m => ganador.Tabla.Nombre)
                </td>
                <td style="width: 15%;">
                    <div class="grid">
                        @foreach (var carta in ganador.Tabla.Cartas)
                        {
                        <div style="position:relative">
                            <img src="@carta.Imagen" class="card-img-top" alt="El gallo">
                            <img src="img/check.png" class="marcado" alt="check">
                        </div>
                        }
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Loteria/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <img src="img/loteria.png" />
</div>

Loteria/Views/Loteria/Index.cshtml
<section class="section">
    <div class="container">
        <h1 class="text-center titulo">Loteria</h1>
        <div>
            <button type="button" id="RevolverCartas" onclick="CambiarOrdenCartas()" class="btn btn-outline-primary btn-color">Desordenar cartas</button>
            <button type="button" id="MostrarOcultarCartas" onclick="OcultarMostrarCartas()" class="btn btn-outline-primary btn-color">Ocultar Tarjetas Seleccionadas</button>
            <a asp-area="" asp-controller="Loteria" asp-action="Index" class="btn btn-outline-primary btn-color">Reiniciar Juego</a>
        </div>
        <hr />  
        <div id="cartas">
        </div>
        <hr />
        <div id="tablas" class="row"></div>
    </div>
</section>



<!-- Modal -->
<div class="modal fade" id="ganadores" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ganadoresLabel">Ganadores</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="tablasGanadoras" class="row"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/js/clases.js"></script>
    <script src="~/js/loteria.js"></script>
}

Loteria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Loteria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Loteria.styles.css" asp-append-version="true" />

    <!-- Owl Stylesheets -->
    <link rel="stylesheet" href="~/lib/assets/owlcarousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="~/lib/assets/owlcarousel/assets/owl.theme.default.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Loteria</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loteria" asp-action="Index">Juego</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ganadores" asp-action="Index">Historico</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div id="loader" class="loader" style="display:none">
        <img src="img/progress-icon.gif" />
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p style="color:#fff">Loteria</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @* Axios *@
    <script src="~/lib/axios.min.js"></script>

    <!-- Owl javascript -->
    <script src="~/lib/assets/vendors/jquery.min.js"></script>
    <script src="~/lib/assets/owlcarousel/owl.carousel.js"></script>

    <script src="~/lib/assets/vendors/highlight.js"></script>
    <script src="~/lib/assets/js/app.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>